In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

dataset = pd.read_csv('C:/Users/black/Downloads/Data.csv')
dataset.head()

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
print("Матрица признаков"); print(X)
print("Зависимая переменная"); print(y)

imputer = SimpleImputer(missing_values = 'NaN', strategy = 'mean')
#imputer = imputer.fit(X[:, 1:3])
#X = imputer.transform(X[:, 1:3])
print(X)

labelencoder_y = LabelEncoder()
print("Зависимая переменная до обработки")
print(y)
y = labelencoder_y.fit_transform(y)
print(y)

labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])
#onehotencoder = OneHotEncoder(categorical_features = [0])
#X = onehotencoder.fit_transform(X).toarray()
print("Перекодировка категориального признака")
print(X)

X_dirty = X.copy()
X_dirty

transformers = [
    ('onehot', OneHotEncoder(), [0]),
    ('imp', SimpleImputer(), [1, 2])
]
ct = ColumnTransformer(transformers)
X_transformed = ct.fit_transform(X_dirty)
print(X_transformed.shape)
X_transformed

X_data = pd.DataFrame(
    X_transformed,
    columns=['C1', 'C2', 'C3', 'Age', 'Salary'])
X_data

Матрица признаков
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
Зависимая переменная
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
Зависимая переменная до обработки
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
[0 1 0 0 1 1 0 1 0 1]
Перекодировка категориального признака
[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 nan]
 [0 35.0 58000.0]
 [2 nan 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]
(10, 5)

    C1   C2   C3        Age        Salary
0  1.0  0.0  0.0  44.000000  72000.000000
1  0.0  0.0  1.0  27.000000  48000.000000
2  0.0  1.0  0.0  30.000000  54000.000000
3  0.0  0.0  1.0  38.000000  61000.000000
4  0.0  1.0  0.0  40.000000  63777.777778
5  1.0  0.0  0.0  35.000000  58000.000000
6  0.0  0.0  1.0  38.777778  52000.000000
7  1.0  0.0  0.0  48.000000  79000.000000
8  0.0  1.0  0.0  50.000000  83000.000000
9  1.0  0.0  0.0  37.000000  67000.000000